//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectionManagerEntities : DbContext
    {
        public CollectionManagerEntities()
            : base("name=CollectionManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<CheckList> CheckLists { get; set; }
        public virtual DbSet<CheckListResult> CheckListResults { get; set; }
        public virtual DbSet<CollectionDetail> CollectionDetails { get; set; }
        public virtual DbSet<CollectionType> CollectionTypes { get; set; }
        public virtual DbSet<Contribution> Contributions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Guarantor> Guarantors { get; set; }
        public virtual DbSet<Lga> Lgas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserUnit> UserUnits { get; set; }
        public virtual DbSet<UserUnitHistory> UserUnitHistories { get; set; }
        public virtual DbSet<VechicleDetail> VechicleDetails { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    }
}
