//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleType()
        {
            this.CheckLists = new HashSet<CheckList>();
        }
    
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckList> CheckLists { get; set; }
        public virtual User User { get; set; }
    }
}
